config/routes.rb
Rails.application.routes.draw do
  resources :foos

end

app/models/foo.rb
class Foo < ActiveRecord::Base
  serialize :jids, Array

  def do_job
    test_jids = []


    jids << "s"
    test_jids << "s"
    Rails.logger.info("s has been pushed")
    Rails.logger.info(jids)
    Rails.logger.info(test_jids)

    jids << BarWorker.perform_in(10.minutes, self.id)
    test_jids << BarWorker.perform_in(10.minutes, self.id)
    Rails.logger.info("normal worker has been pushed")
    Rails.logger.info(jids)
    Rails.logger.info(test_jids)

    jids << FooMailer.delay_for(10.minutes).confirm_foo(self)
    test_jids << FooMailer.delay_for(10.minutes).confirm_foo(self)
    Rails.logger.info("mailer worker id pushed")
    Rails.logger.info(jids)
    Rails.logger.info(test_jids)

    jids
  end



  def do_job_with_assignment
    test_jids = []

    jids << "s"
    test_jids << "s"
    Rails.logger.info("s has been pushed")
    Rails.logger.info(jids)
    Rails.logger.info(test_jids)


    bar_worker_jid = BarWorker.perform_in(10.minutes, self.id)
    jids << bar_worker_jid

    test_bar_worker_jid = BarWorker.perform_in(10.minutes, self.id)
    test_jids << test_bar_worker_jid
    Rails.logger.info("normal worker has been pushed")
    Rails.logger.info(jids)
    Rails.logger.info(test_jids)

    foo_mailer_jid = FooMailer.delay_for(10.minutes).confirm_foo(self)
    jids << foo_mailer_jid

    test_foo_mailer_jid = FooMailer.delay_for(10.minutes).confirm_foo(self)
    test_jids << test_foo_mailer_jid
    Rails.logger.info("mailer worker id pushed")
    Rails.logger.info(jids)
    Rails.logger.info(test_jids)

    jids
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foos_controller.rb
class FoosController < ApplicationController
  before_action :set_foo, only: [:show, :edit, :update, :destroy]

  # GET /foos
  # GET /foos.json
  def index
    @foos = Foo.all
  end

  # GET /foos/1
  # GET /foos/1.json
  def show
  end

  # GET /foos/new
  def new
    @foo = Foo.new
  end

  # GET /foos/1/edit
  def edit
  end

  # POST /foos
  # POST /foos.json
  def create
    @foo = Foo.new(foo_params)

    respond_to do |format|
      if @foo.save
        format.html { redirect_to @foo, notice: 'Foo was successfully created.' }
        format.json { render :show, status: :created, location: @foo }
      else
        format.html { render :new }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foos/1
  # PATCH/PUT /foos/1.json
  def update
    respond_to do |format|
      if @foo.update(foo_params)
        format.html { redirect_to @foo, notice: 'Foo was successfully updated.' }
        format.json { render :show, status: :ok, location: @foo }
      else
        format.html { render :edit }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foos/1
  # DELETE /foos/1.json
  def destroy
    @foo.destroy
    respond_to do |format|
      format.html { redirect_to foos_url, notice: 'Foo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foo
      @foo = Foo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foo_params
      params.require(:foo).permit(:title, :name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foos_helper.rb
module FoosHelper
end

app/views/foos/_form.html.erb
<%= form_for(@foo) do |f| %>
  <% if @foo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
      <% @foo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foos/edit.html.erb
<h1>Editing foo</h1>

<%= render 'form' %>

<%= link_to 'Show', @foo %> |
<%= link_to 'Back', foos_path %>

app/views/foos/index.html.erb
<h1>Listing foos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Name</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foos.each do |foo| %>
      <tr>
        <td><%= foo.title %></td>
        <td><%= foo.name %></td>
        <td><%= foo.body %></td>
        <td><%= link_to 'Show', foo %></td>
        <td><%= link_to 'Edit', edit_foo_path(foo) %></td>
        <td><%= link_to 'Destroy', foo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foo', new_foo_path %>

app/views/foos/new.html.erb
<h1>New foo</h1>

<%= render 'form' %>

<%= link_to 'Back', foos_path %>

app/views/foos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @foo.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @foo.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @foo.body %>
</p>

<%= link_to 'Edit', edit_foo_path(@foo) %> |
<%= link_to 'Back', foos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SidekiqTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>